# Generated by Django 4.1.3 on 2023-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0002_uploadedimage_position_x_uploadedimage_position_y"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="position_x",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="position_y",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
