# Generated by Django 4.1.3 on 2023-10-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0003_alter_uploadedimage_position_x_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="position_x",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="position_y",
            field=models.PositiveBigIntegerField(),
        ),
    ]
