# Generated by Django 4.1.3 on 2023-10-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0004_alter_uploadedimage_position_x_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="position_x",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="position_y",
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image1",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image10",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image2",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image3",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image4",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image5",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image6",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image7",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image8",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="image9",
            field=models.ImageField(default="placeholder.png", upload_to="images/"),
        ),
    ]
