# Generated by Django 4.1.3 on 2023-10-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0005_remove_uploadedimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image10",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image6",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image7",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image8",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="image9",
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image1",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
