# Generated by Django 4.1.3 on 2023-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0006_remove_uploadedimage_image10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image1",
            field=models.ImageField(blank="True ", null="True", upload_to="images/"),
        ),
    ]
