# Generated by Django 4.1.3 on 2023-10-04 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0008_alter_uploadedimage_image1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedImage",
            new_name="KthemeImages",
        ),
    ]
