# Generated by Django 4.1.3 on 2023-10-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0010_rename_kthemeimages_kthemeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.DeleteModel(
            name="KthemeImage",
        ),
    ]
