# Generated by Django 4.1.3 on 2023-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("make_ktheme", "0011_image_delete_kthemeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="KthemeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(blank="True", null="True", upload_to="images/"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
