# Generated by Django 4.1.3 on 2023-10-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("make_ktheme", "0013_delete_kthemeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ktheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dir_path", models.CharField(max_length=500)),
                ("s_1_x", models.PositiveIntegerField()),
                ("s_1_y", models.PositiveIntegerField()),
                ("s_1_t", models.PositiveIntegerField()),
                ("s_1_l", models.PositiveIntegerField()),
                ("s_1_b", models.PositiveIntegerField()),
                ("s_1_r", models.PositiveIntegerField()),
                ("s_2_x", models.PositiveIntegerField()),
                ("s_2_y", models.PositiveIntegerField()),
                ("s_2_t", models.PositiveIntegerField()),
                ("s_2_l", models.PositiveIntegerField()),
                ("s_2_b", models.PositiveIntegerField()),
                ("s_2_r", models.PositiveIntegerField()),
                ("r_1_x", models.PositiveIntegerField()),
                ("r_1_y", models.PositiveIntegerField()),
                ("r_1_t", models.PositiveIntegerField()),
                ("r_1_l", models.PositiveIntegerField()),
                ("r_1_b", models.PositiveIntegerField()),
                ("r_1_r", models.PositiveIntegerField()),
                ("r_2_x", models.PositiveIntegerField()),
                ("r_2_y", models.PositiveIntegerField()),
                ("r_2_t", models.PositiveIntegerField()),
                ("r_2_l", models.PositiveIntegerField()),
                ("r_2_b", models.PositiveIntegerField()),
                ("r_2_r", models.PositiveIntegerField()),
            ],
        ),
    ]
