# Generated by Django 4.1.3 on 2023-10-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("make_ktheme", "0014_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ktheme",
            name="bg_color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="ktheme",
            name="input_bg_color",
            field=models.CharField(default="#D3D3D3", max_length=7),
        ),
        migrations.AddField(
            model_name="ktheme",
            name="main_text_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
        migrations.AddField(
            model_name="ktheme",
            name="point_text_color",
            field=models.CharField(default="#FFC0CB", max_length=7),
        ),
        migrations.AddField(
            model_name="ktheme",
            name="receive_text_color",
            field=models.CharField(default="#808080", max_length=7),
        ),
        migrations.AddField(
            model_name="ktheme",
            name="send_text_color",
            field=models.CharField(default="#A9A9A9", max_length=7),
        ),
        migrations.AddField(
            model_name="ktheme",
            name="theme_id",
            field=models.CharField(default="themeId", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ktheme",
            name="theme_name",
            field=models.CharField(default="themeName", max_length=100),
            preserve_default=False,
        ),
    ]
