# Generated by Django 4.1.3 on 2023-10-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("make_ktheme", "0016_remove_ktheme_bg_color_remove_ktheme_dir_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csscolor",
            name="ktheme",
        ),
        migrations.RemoveField(
            model_name="ktheme",
            name="user",
        ),
        migrations.DeleteModel(
            name="CssBubble",
        ),
        migrations.DeleteModel(
            name="CssColor",
        ),
        migrations.DeleteModel(
            name="Ktheme",
        ),
    ]
