# Generated by Django 4.1.3 on 2023-10-24 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ktheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_name", models.CharField(max_length=50)),
                ("theme_id", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CssColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bg_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("main_text_color", models.CharField(default="#000000", max_length=7)),
                ("point_text_color", models.CharField(default="#FFC0CB", max_length=7)),
                ("input_bg_color", models.CharField(default="#D3D3D3", max_length=7)),
                ("send_text_color", models.CharField(default="#A9A9A9", max_length=7)),
                (
                    "receive_text_color",
                    models.CharField(default="#808080", max_length=7),
                ),
                (
                    "ktheme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.ktheme"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CssBubble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_1_x", models.PositiveIntegerField(default=17)),
                ("s_1_y", models.PositiveIntegerField(default=17)),
                ("s_1_t", models.PositiveIntegerField(default=10)),
                ("s_1_l", models.PositiveIntegerField(default=11)),
                ("s_1_b", models.PositiveIntegerField(default=9)),
                ("s_1_r", models.PositiveIntegerField(default=17)),
                ("s_2_x", models.PositiveIntegerField(default=17)),
                ("s_2_y", models.PositiveIntegerField(default=17)),
                ("s_2_t", models.PositiveIntegerField(default=10)),
                ("s_2_l", models.PositiveIntegerField(default=11)),
                ("s_2_b", models.PositiveIntegerField(default=9)),
                ("s_2_r", models.PositiveIntegerField(default=17)),
                ("r_1_x", models.PositiveIntegerField(default=20)),
                ("r_1_y", models.PositiveIntegerField(default=17)),
                ("r_1_t", models.PositiveIntegerField(default=10)),
                ("r_1_l", models.PositiveIntegerField(default=17)),
                ("r_1_b", models.PositiveIntegerField(default=9)),
                ("r_1_r", models.PositiveIntegerField(default=11)),
                ("r_2_x", models.PositiveIntegerField(default=20)),
                ("r_2_y", models.PositiveIntegerField(default=17)),
                ("r_2_t", models.PositiveIntegerField(default=10)),
                ("r_2_l", models.PositiveIntegerField(default=17)),
                ("r_2_b", models.PositiveIntegerField(default=9)),
                ("r_2_r", models.PositiveIntegerField(default=11)),
                (
                    "ktheme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.ktheme"
                    ),
                ),
            ],
        ),
    ]
