# Generated by Django 4.1.3 on 2023-10-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cssbubble",
            name="ktheme",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="css_bubble",
                to="main.ktheme",
            ),
        ),
        migrations.AlterField(
            model_name="csscolor",
            name="ktheme",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="css_color",
                to="main.ktheme",
            ),
        ),
    ]
