# Generated by Django 4.1.3 on 2023-11-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KthemeImage",
        ),
    ]
