# Generated by Django 4.1.3 on 2023-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_kthemeimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cssbubble",
            name="r_1_l",
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="r_1_r",
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="r_1_x",
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="r_2_l",
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="r_2_r",
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="r_2_x",
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="s_1_l",
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="s_1_r",
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="s_1_x",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="s_2_l",
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="s_2_r",
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AlterField(
            model_name="cssbubble",
            name="s_2_x",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
