# Generated by Django 4.1.3 on 2023-11-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_kthemeimages_chat_bg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KthemeImages",
        ),
    ]
