# Generated by Django 5.1 on 2026-07-02 07:23

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_csscolor_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cssbubble',
            name='r_1_b',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_1_l',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_1_r',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_1_t',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_1_x',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_1_y',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_2_b',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_2_l',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_2_r',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_2_t',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_2_x',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='r_2_y',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_1_b',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_1_l',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_1_r',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_1_t',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_1_x',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_1_y',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_2_b',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_2_l',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_2_r',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_2_t',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_2_x',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cssbubble',
            name='s_2_y',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='csscolor',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='배경'),
        ),
        migrations.AlterField(
            model_name='csscolor',
            name='input_bg_color',
            field=models.CharField(default='#D3D3D3', max_length=7, verbose_name='입력창'),
        ),
        migrations.AlterField(
            model_name='csscolor',
            name='main_text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='메인 텍스트'),
        ),
        migrations.AlterField(
            model_name='csscolor',
            name='point_text_color',
            field=models.CharField(default='#414141', max_length=7, verbose_name='강조 텍스트'),
        ),
        migrations.AlterField(
            model_name='csscolor',
            name='receive_text_color',
            field=models.CharField(default='#000001', max_length=7, verbose_name='받은 말풍선 텍스트'),
        ),
        migrations.AlterField(
            model_name='csscolor',
            name='send_text_color',
            field=models.CharField(default='#000002', max_length=7, verbose_name='보낸 말풍선 텍스트'),
        ),
        migrations.AlterField(
            model_name='ktheme',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[main.models.validate_theme_id]),
        ),
    ]
