# Generated by Django 4.1.3 on 2023-10-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_kthemeimage_delete_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KthemeImage",
        ),
    ]
